#!/usr/bin/env bash
# apply-branding.sh — read config/branding.yaml and stamp the per-city values
# into all three components (backend, admin, mobile) so a fresh checkout
# becomes a city-branded build in one command.
#
# Requirements:
#   - yq v4 (for YAML parsing)            https://github.com/mikefarah/yq
#   - jq                                  https://jqlang.github.io/jq/
#
# Usage:
#   ./scripts/apply-branding.sh                  # use config/branding.yaml
#   ./scripts/apply-branding.sh path/to/cfg.yaml # use a different file
#
# Idempotent: re-running with the same config produces the same output.

set -euo pipefail

CONFIG_FILE="${1:-config/branding.yaml}"
ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

if ! command -v yq >/dev/null 2>&1; then
  echo "✗ yq is required: https://github.com/mikefarah/yq/#install" >&2
  exit 1
fi

if [ ! -f "$CONFIG_FILE" ]; then
  echo "✗ config file not found: $CONFIG_FILE" >&2
  exit 1
fi

echo "▶ Applying branding from $CONFIG_FILE"

# --- Read values -----------------------------------------------------------------
BRAND_NAME_AR=$(yq '.brand.name_ar' "$CONFIG_FILE")
BRAND_NAME_EN=$(yq '.brand.name_en' "$CONFIG_FILE")
BRAND_SHORT=$(yq '.brand.short_code' "$CONFIG_FILE")
PRIMARY=$(yq '.brand.primary_color' "$CONFIG_FILE")
ACCENT=$(yq '.brand.accent_color' "$CONFIG_FILE")
DOMAIN=$(yq '.brand.domain' "$CONFIG_FILE")
SUPPORT_EMAIL=$(yq '.brand.support_email' "$CONFIG_FILE")

CITY_AR=$(yq '.region.city_ar' "$CONFIG_FILE")
CITY_EN=$(yq '.region.city_en' "$CONFIG_FILE")
COUNTRY_CODE=$(yq '.region.country_code' "$CONFIG_FILE")
CENTER_LAT=$(yq '.region.center_lat' "$CONFIG_FILE")
CENTER_LNG=$(yq '.region.center_lng' "$CONFIG_FILE")
RADIUS_KM=$(yq '.region.service_radius_km' "$CONFIG_FILE")
TIMEZONE=$(yq '.region.timezone' "$CONFIG_FILE")

LOCALE=$(yq '.locale.primary' "$CONFIG_FILE")
CURRENCY=$(yq '.currency.code' "$CONFIG_FILE")
SMS_PROVIDER=$(yq '.sms.provider' "$CONFIG_FILE")
PAYMENT_PROVIDER=$(yq '.payment.provider' "$CONFIG_FILE")
COMMISSION=$(yq '.business.commission_pct' "$CONFIG_FILE")
SERVICE_FEE=$(yq '.business.service_fee_pct' "$CONFIG_FILE")
URGENT_FEE=$(yq '.business.urgent_fee_pct' "$CONFIG_FILE")
MIN_WITHDRAW=$(yq '.business.min_withdrawal' "$CONFIG_FILE")

# --- Backend .env --------------------------------------------------------------
BACKEND_ENV="backend/.env"
if [ -f "$BACKEND_ENV" ]; then
  echo "▶ Updating $BACKEND_ENV"
  python3 - "$BACKEND_ENV" \
    SMS_PROVIDER="$SMS_PROVIDER" \
    PAYMENT_PROVIDER="$PAYMENT_PROVIDER" \
    DEFAULT_COMMISSION="$COMMISSION" \
    DEFAULT_SERVICE_FEE="$SERVICE_FEE" \
    URGENT_FEE="$URGENT_FEE" \
    MIN_WITHDRAWAL="$MIN_WITHDRAW" <<'PY'
import sys, re
path = sys.argv[1]
updates = dict(arg.split('=', 1) for arg in sys.argv[2:])
with open(path) as f:
    lines = f.readlines()
seen = set()
out = []
for line in lines:
    m = re.match(r'^([A-Z_]+)=', line)
    if m and m.group(1) in updates:
        key = m.group(1)
        out.append(f"{key}={updates[key]}\n")
        seen.add(key)
    else:
        out.append(line)
for key, val in updates.items():
    if key not in seen:
        out.append(f"{key}={val}\n")
with open(path, 'w') as f:
    f.writelines(out)
PY
else
  echo "⚠ $BACKEND_ENV does not exist — copying from .env.example first"
  cp backend/.env.example "$BACKEND_ENV"
fi

# --- Admin .env.local ----------------------------------------------------------
ADMIN_ENV="admin-dashboard/.env.local"
if [ -f "$ADMIN_ENV" ]; then
  echo "▶ Updating $ADMIN_ENV"
  python3 - "$ADMIN_ENV" "NEXT_PUBLIC_APP_NAME=$BRAND_NAME_EN Admin" <<'PY'
import sys, re
path = sys.argv[1]
updates = dict(arg.split('=', 1) for arg in sys.argv[2:])
with open(path) as f:
    lines = f.readlines()
seen = set()
out = []
for line in lines:
    m = re.match(r'^([A-Z_]+)=', line)
    if m and m.group(1) in updates:
        key = m.group(1)
        out.append(f"{key}={updates[key]}\n")
        seen.add(key)
    else:
        out.append(line)
for key, val in updates.items():
    if key not in seen:
        out.append(f"{key}={val}\n")
with open(path, 'w') as f:
    f.writelines(out)
PY
fi

# --- Mobile Flutter branding.dart ----------------------------------------------
MOBILE_BRANDING="mobile/lib/config/branding.dart"
echo "▶ Writing $MOBILE_BRANDING"
mkdir -p "$(dirname "$MOBILE_BRANDING")"
cat > "$MOBILE_BRANDING" <<EOF
// AUTO-GENERATED by scripts/apply-branding.sh — DO NOT EDIT BY HAND
// Edit config/branding.yaml and rerun the script.

class Branding {
  static const String nameAr = '$BRAND_NAME_AR';
  static const String nameEn = '$BRAND_NAME_EN';
  static const String shortCode = '$BRAND_SHORT';

  static const String cityAr = '$CITY_AR';
  static const String cityEn = '$CITY_EN';
  static const String countryCode = '$COUNTRY_CODE';
  static const String timezone = '$TIMEZONE';

  static const double centerLat = $CENTER_LAT;
  static const double centerLng = $CENTER_LNG;
  static const int serviceRadiusKm = $RADIUS_KM;

  static const String locale = '$LOCALE';
  static const String currency = '$CURRENCY';

  static const String primaryColor = '$PRIMARY';
  static const String accentColor = '$ACCENT';

  static const String domain = '$DOMAIN';
  static const String supportEmail = '$SUPPORT_EMAIL';
}
EOF

# --- pubspec name --------------------------------------------------------------
if [ -f mobile/pubspec.yaml ]; then
  echo "▶ Updating mobile/pubspec.yaml description"
  yq -i '.description = strenv(DESC)' DESC="$BRAND_NAME_AR - $BRAND_NAME_EN" mobile/pubspec.yaml
fi

# --- admin package.json --------------------------------------------------------
if [ -f admin-dashboard/package.json ]; then
  echo "▶ Updating admin-dashboard/package.json name"
  jq --arg n "$BRAND_SHORT-admin" '.name = $n' admin-dashboard/package.json > admin-dashboard/package.json.tmp
  mv admin-dashboard/package.json.tmp admin-dashboard/package.json
fi

# --- Summary -------------------------------------------------------------------
cat <<EOF

✔ Branding applied:
    Brand         $BRAND_NAME_AR / $BRAND_NAME_EN ($BRAND_SHORT)
    City          $CITY_AR / $CITY_EN  ($CENTER_LAT, $CENTER_LNG, ${RADIUS_KM} km)
    Locale        $LOCALE              Currency $CURRENCY
    SMS provider  $SMS_PROVIDER
    Payment       $PAYMENT_PROVIDER
    Commission    ${COMMISSION}%       Service fee ${SERVICE_FEE}%
    Domain        $DOMAIN

Next steps:
  1. Drop your logo + splash into ./branding/ (paths in $CONFIG_FILE)
  2. cd backend && npm run build && npm run seed:all
  3. cd ../admin-dashboard && npm run build
  4. cd ../mobile && flutter pub get && flutter build apk --release
EOF
